### ISSUE TITLE
Unexpected FileNotFoundException

### ISSUE THREAD

**Issue by MariusVolkhart** [box/box-android-content-sdk#13]
`BoxApiFile#getDownloadRequest(File, String)` throws a `FileNotFoundException` when calling `File#exists()` on the provided `File` returns `false`. This seems very strange.

I'm passing the `File` reference to Box because I want to create the file. I actually performed a delete right before the call to `getDownloadRequest()` to ensure that no other parts of the system are using that file.

A `File` not existing doesn't mean that it can't be written to. The `FileOutputStream` will create it. In fact, from the `File#createNewFile()` documentation:
> This method is not generally useful... For reading/writing files, use `FileInputStream`, `FileOutputStream`, or `RandomAccessFile`, all of which can create files.

which suggests that passing a `File` that doesn't exist should be fine.

https://github.com/box/box-android-content-sdk/blob/master/box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiFile.java#L298

**Comment by doncung** [comment]
That logic was added to help identify problems with an invalid File being passed in as early as possible. Because the request can potentially executed in a different place at a different time and usually in a different thread, the decision was made to add a quick check during construction of the request instead of when the file is first used to help developer's identify the issue. The check isn't  necessary for the code to run, so based on developer feedback we'd certainly consider removing it.
